### ISSUE TITLE
Need installation instructions in this repo for installing it

### ISSUE THREAD

**Issue by scottbea** [Jumpathy/BetterChatV3#1]
There are links to some emerging API docs as well as to the Roblox Dev Forum conversation.  I recommend adding a better `SETUP.md` or something in this repo that captures the latest, more accurate details of how to install it.

**Comment by scottbea** [comment]
For example, options are:

* **AutoUpdater** script that you can save as a plugin and have it install the latest.. (but permissions block for some)
* Roblox project files with sample scripts that load **BetterChatV3**.  
  * Example: [here](https://github.com/RuizuKun-Dev/Better-Chat-V3).
* Write your own code to load the module

**Comment by Jumpathy** [comment]
I got you!

**Comment by Jumpathy** [comment]
Done, let me know if there's any other requests.
