### ISSUE TITLE
One shows gui error.

### ISSUE THREAD

**Issue by MuFengStudio** [Jumpathy/BetterChatV3#2]
![image](https://github.com/user-attachments/assets/a6a9c1a6-3c2e-4728-976f-30ff441774ad)
One shows gui error. I have installed Better Chat (latest version). I put it into Roblox ServerScriptService. But the chat box of roblox still shows

**Comment by Jumpathy** [comment]
Go to TextChatService in the explorer, and set ‘ChatVersion’ to ‘LegacyChatService’ 4, Go to the model tab in studio, Advanced (on the far right), Service, and insert ‘Chat’.
From here, all you need to do is turn off ‘LoadDefaultChat’ and ‘BubbleChatEnabled’

**Comment by MuFengStudio** [comment]
> 在资源管理器中转到 TextChatService，并将“ChatVersion”设置为“LegacyChatService” 4，转到工作室中的模型选项卡，高级（最右侧），服务，然后插入“聊天”。 从这里，您需要做的就是关闭“LoadDefaultChat”和“BubbleChatEnabled”

ok thank you,i will try

**Comment by MuFengStudio** [comment]
> 在资源管理器中转到 TextChatService，并将“ChatVersion”设置为“LegacyChatService” 4，转到工作室中的模型选项卡，高级（最右侧），服务，然后插入“聊天”。 从这里，您需要做的就是关闭“LoadDefaultChat”和“BubbleChatEnabled”

Thanks a lot. It works.
